"""
Generates 500 wind turbine tags inspired by IEC 61400-25 logical nodes.
Outputs both CSV and JSON.
"""
import csv
import json

tags = []
_id = [1]  # mutable counter

def add(name, desc, unit, dtype, vmin, vmax, category, interval=1, critical=False):
    tags.append({
        "tag_id": _id[0],
        "tag_name": name,
        "description": desc,
        "unit": unit,
        "data_type": dtype,
        "min_value": vmin,
        "max_value": vmax,
        "category": category,
        "update_interval_sec": interval,
        "is_critical": critical,
    })
    _id[0] += 1

PREFIX = "WTG01"

# =========================================================
# 1) GENERAL / STATUS  (25)
# =========================================================
cat = "General"
add(f"{PREFIX}.GEN.OperatingState",        "Current operating state code (0=stop,1=idle,2=start,3=run,4=fault)", "code",  "INT",   0, 10, cat, 1, True)
add(f"{PREFIX}.GEN.OperatingMode",         "Operating mode (manual/auto/remote/service)",                        "code",  "INT",   0, 5,  cat, 1)
add(f"{PREFIX}.GEN.RunTime_Total",         "Total run time of the turbine",                                      "h",     "FLOAT", 0, 1e6, cat, 60)
add(f"{PREFIX}.GEN.RunTime_Today",         "Run time today",                                                     "h",     "FLOAT", 0, 24, cat, 60)
add(f"{PREFIX}.GEN.StopTime_Total",        "Total stop time",                                                    "h",     "FLOAT", 0, 1e6, cat, 60)
add(f"{PREFIX}.GEN.FaultCount_Total",      "Cumulative fault count",                                             "count", "INT",   0, 1e6, cat, 10)
add(f"{PREFIX}.GEN.FaultCount_Today",      "Fault count today",                                                  "count", "INT",   0, 1000, cat, 10)
add(f"{PREFIX}.GEN.LastFaultCode",         "Last fault code",                                                    "code",  "INT",   0, 9999, cat, 5)
add(f"{PREFIX}.GEN.LastFaultTimestamp",    "Last fault timestamp (epoch seconds)",                               "s",     "INT",   0, 2e10, cat, 5)
add(f"{PREFIX}.GEN.Availability_Today",    "Turbine availability today",                                         "%",     "FLOAT", 0, 100, cat, 60)
add(f"{PREFIX}.GEN.Availability_Month",    "Turbine availability this month",                                    "%",     "FLOAT", 0, 100, cat, 300)
add(f"{PREFIX}.GEN.Availability_Year",     "Turbine availability this year",                                     "%",     "FLOAT", 0, 100, cat, 300)
add(f"{PREFIX}.GEN.MaintenanceMode",       "Is turbine in maintenance mode (0/1)",                               "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.GEN.RemoteControlEnabled",  "Remote control enabled",                                             "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.GEN.GridConnected",         "Connected to grid",                                                  "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.GEN.CommunicationOK",       "SCADA communication healthy",                                        "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.GEN.HeartbeatCounter",      "Controller heartbeat counter",                                       "count", "INT",   0, 65535, cat, 1)
add(f"{PREFIX}.GEN.ControllerVersion",     "Controller firmware version",                                        "ver",   "STRING", 0, 0, cat, 3600)
add(f"{PREFIX}.GEN.SerialNumber",          "Turbine serial number",                                              "id",    "STRING", 0, 0, cat, 3600)
add(f"{PREFIX}.GEN.Model",                 "Turbine model name",                                                 "name",  "STRING", 0, 0, cat, 3600)
add(f"{PREFIX}.GEN.RatedPower",            "Rated nameplate power",                                              "kW",    "FLOAT", 0, 20000, cat, 3600)
add(f"{PREFIX}.GEN.CutInWindSpeed",        "Cut-in wind speed setpoint",                                         "m/s",   "FLOAT", 0, 10, cat, 3600)
add(f"{PREFIX}.GEN.CutOutWindSpeed",       "Cut-out wind speed setpoint",                                        "m/s",   "FLOAT", 15, 35, cat, 3600)
add(f"{PREFIX}.GEN.RatedWindSpeed",        "Rated wind speed",                                                   "m/s",   "FLOAT", 8, 20, cat, 3600)
add(f"{PREFIX}.GEN.CurtailmentActive",     "Power curtailment active",                                           "bool",  "BOOL",  0, 1, cat, 5)

# =========================================================
# 2) METEOROLOGICAL (35)
# =========================================================
cat = "Meteorological"
add(f"{PREFIX}.MET.WindSpeed_Inst",        "Instantaneous wind speed at hub height",                             "m/s",   "FLOAT", 0, 40, cat, 1, True)
add(f"{PREFIX}.MET.WindSpeed_Avg_1min",    "1-minute average wind speed",                                        "m/s",   "FLOAT", 0, 40, cat, 60)
add(f"{PREFIX}.MET.WindSpeed_Avg_10min",   "10-minute average wind speed",                                       "m/s",   "FLOAT", 0, 40, cat, 60)
add(f"{PREFIX}.MET.WindSpeed_Max_10min",   "10-minute max wind speed (gust)",                                    "m/s",   "FLOAT", 0, 60, cat, 60)
add(f"{PREFIX}.MET.WindSpeed_Min_10min",   "10-minute min wind speed",                                           "m/s",   "FLOAT", 0, 40, cat, 60)
add(f"{PREFIX}.MET.WindSpeed_StdDev_10min","10-minute std deviation wind speed",                                 "m/s",   "FLOAT", 0, 10, cat, 60)
add(f"{PREFIX}.MET.WindDirection_Inst",    "Instantaneous wind direction",                                       "deg",   "FLOAT", 0, 360, cat, 1)
add(f"{PREFIX}.MET.WindDirection_Avg_10min","10-minute average wind direction",                                  "deg",   "FLOAT", 0, 360, cat, 60)
add(f"{PREFIX}.MET.TurbulenceIntensity",   "Turbulence intensity",                                               "%",     "FLOAT", 0, 50, cat, 60)
add(f"{PREFIX}.MET.WindShear",             "Wind shear coefficient",                                             "-",     "FLOAT", -1, 2, cat, 60)
add(f"{PREFIX}.MET.WindVeer",              "Wind veer (deg per meter)",                                          "deg/m", "FLOAT", -5, 5, cat, 60)
add(f"{PREFIX}.MET.AmbientTemp",           "Ambient air temperature at nacelle",                                 "°C",    "FLOAT", -50, 60, cat, 5)
add(f"{PREFIX}.MET.AmbientHumidity",       "Ambient relative humidity",                                          "%",     "FLOAT", 0, 100, cat, 5)
add(f"{PREFIX}.MET.AmbientPressure",       "Ambient barometric pressure",                                        "hPa",   "FLOAT", 800, 1100, cat, 10)
add(f"{PREFIX}.MET.AirDensity",            "Calculated air density",                                             "kg/m^3","FLOAT", 0.8, 1.4, cat, 10)
add(f"{PREFIX}.MET.Anemometer1_Speed",     "Anemometer #1 wind speed",                                           "m/s",   "FLOAT", 0, 40, cat, 1)
add(f"{PREFIX}.MET.Anemometer2_Speed",     "Anemometer #2 wind speed (redundant)",                               "m/s",   "FLOAT", 0, 40, cat, 1)
add(f"{PREFIX}.MET.Anemometer1_Heated",    "Anemometer #1 heater on",                                            "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.MET.Anemometer2_Heated",    "Anemometer #2 heater on",                                            "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.MET.WindVane1_Angle",       "Wind vane #1 angle",                                                 "deg",   "FLOAT", 0, 360, cat, 1)
add(f"{PREFIX}.MET.WindVane2_Angle",       "Wind vane #2 angle (redundant)",                                     "deg",   "FLOAT", 0, 360, cat, 1)
add(f"{PREFIX}.MET.Precipitation",         "Precipitation detected",                                             "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.MET.IceDetected",           "Ice formation detected on sensors",                                  "bool",  "BOOL",  0, 1, cat, 5, True)
add(f"{PREFIX}.MET.SolarRadiation",        "Solar radiation",                                                    "W/m^2", "FLOAT", 0, 1500, cat, 30)
add(f"{PREFIX}.MET.LightningStrikes_Today","Lightning strikes counted today",                                    "count", "INT",   0, 1000, cat, 60)
add(f"{PREFIX}.MET.LightningStrikes_Total","Lightning strikes total",                                            "count", "INT",   0, 1e6, cat, 300)
add(f"{PREFIX}.MET.CloudHeight",           "Cloud base height (if measured)",                                    "m",     "FLOAT", 0, 5000, cat, 60)
add(f"{PREFIX}.MET.Visibility",            "Visibility (if measured)",                                           "m",     "FLOAT", 0, 50000, cat, 60)
add(f"{PREFIX}.MET.DewPoint",              "Dew point temperature",                                              "°C",    "FLOAT", -50, 50, cat, 30)
add(f"{PREFIX}.MET.WindSpeed_30m",         "Wind speed at 30m mast height",                                      "m/s",   "FLOAT", 0, 40, cat, 1)
add(f"{PREFIX}.MET.WindSpeed_60m",         "Wind speed at 60m mast height",                                      "m/s",   "FLOAT", 0, 40, cat, 1)
add(f"{PREFIX}.MET.WindSpeed_90m",         "Wind speed at 90m mast height",                                      "m/s",   "FLOAT", 0, 40, cat, 1)
add(f"{PREFIX}.MET.YawError",              "Yaw misalignment (wind dir - nacelle dir)",                          "deg",   "FLOAT", -180, 180, cat, 1)
add(f"{PREFIX}.MET.AvgYawError_10min",     "10-minute average yaw error",                                        "deg",   "FLOAT", -180, 180, cat, 60)
add(f"{PREFIX}.MET.ColdWeatherMode",       "Cold weather operation mode active",                                 "bool",  "BOOL",  0, 1, cat, 30)

# =========================================================
# 3) ROTOR & BLADES (55)
# =========================================================
cat = "Rotor"
add(f"{PREFIX}.ROT.Speed",                 "Rotor (low-speed shaft) speed",                                      "rpm",   "FLOAT", 0, 30, cat, 1, True)
add(f"{PREFIX}.ROT.Speed_Filtered",        "Filtered rotor speed",                                               "rpm",   "FLOAT", 0, 30, cat, 1)
add(f"{PREFIX}.ROT.Acceleration",          "Rotor acceleration",                                                 "rpm/s", "FLOAT", -5, 5, cat, 1)
add(f"{PREFIX}.ROT.Azimuth",               "Rotor azimuth angle",                                                "deg",   "FLOAT", 0, 360, cat, 1)
add(f"{PREFIX}.ROT.TipSpeed",              "Calculated blade tip speed",                                         "m/s",   "FLOAT", 0, 120, cat, 1)
add(f"{PREFIX}.ROT.TipSpeedRatio",         "Tip speed ratio (TSR)",                                              "-",     "FLOAT", 0, 15, cat, 1)
add(f"{PREFIX}.ROT.ImbalanceMoment",       "Aerodynamic imbalance moment",                                       "kNm",   "FLOAT", 0, 1000, cat, 5)
add(f"{PREFIX}.ROT.HubTemp",               "Rotor hub internal temperature",                                     "°C",    "FLOAT", -40, 80, cat, 10)
add(f"{PREFIX}.ROT.MainBearing_TempDE",    "Main bearing temperature drive end",                                 "°C",    "FLOAT", -20, 120, cat, 5, True)
add(f"{PREFIX}.ROT.MainBearing_TempNDE",   "Main bearing temperature non-drive end",                             "°C",    "FLOAT", -20, 120, cat, 5, True)
add(f"{PREFIX}.ROT.MainBearing_Vibration", "Main bearing vibration RMS",                                         "mm/s",  "FLOAT", 0, 50, cat, 1, True)
add(f"{PREFIX}.ROT.MainShaft_Torque",      "Main shaft torque",                                                  "kNm",   "FLOAT", 0, 5000, cat, 1)
add(f"{PREFIX}.ROT.MainShaft_BendingMoment","Main shaft bending moment",                                         "kNm",   "FLOAT", 0, 5000, cat, 1)
# Blades 1, 2, 3 — repeating measurements
for b in (1, 2, 3):
    add(f"{PREFIX}.ROT.B{b}.PitchAngle",       f"Blade {b} pitch angle",                                         "deg",   "FLOAT", -5, 95, cat, 1, True)
    add(f"{PREFIX}.ROT.B{b}.PitchAngle_SP",    f"Blade {b} pitch angle setpoint",                                "deg",   "FLOAT", -5, 95, cat, 1)
    add(f"{PREFIX}.ROT.B{b}.PitchRate",        f"Blade {b} pitch rate",                                          "deg/s", "FLOAT", -10, 10, cat, 1)
    add(f"{PREFIX}.ROT.B{b}.PitchMotor_Current",f"Blade {b} pitch motor current",                                "A",     "FLOAT", 0, 100, cat, 1)
    add(f"{PREFIX}.ROT.B{b}.PitchMotor_Temp",  f"Blade {b} pitch motor temperature",                             "°C",    "FLOAT", -20, 150, cat, 5)
    add(f"{PREFIX}.ROT.B{b}.PitchBattery_Voltage",f"Blade {b} pitch backup battery voltage",                     "V",     "FLOAT", 0, 60, cat, 10)
    add(f"{PREFIX}.ROT.B{b}.PitchBattery_Temp",f"Blade {b} pitch backup battery temperature",                    "°C",    "FLOAT", -20, 80, cat, 10)
    add(f"{PREFIX}.ROT.B{b}.RootMoment_Flap",  f"Blade {b} root flapwise bending moment",                        "kNm",   "FLOAT", -10000, 10000, cat, 1)
    add(f"{PREFIX}.ROT.B{b}.RootMoment_Edge",  f"Blade {b} root edgewise bending moment",                        "kNm",   "FLOAT", -10000, 10000, cat, 1)
    add(f"{PREFIX}.ROT.B{b}.RootTemp",         f"Blade {b} root structural temperature",                         "°C",    "FLOAT", -40, 80, cat, 30)
    add(f"{PREFIX}.ROT.B{b}.TipDeflection",    f"Blade {b} tip deflection (optical/strain)",                     "m",     "FLOAT", -10, 10, cat, 1)
    add(f"{PREFIX}.ROT.B{b}.IceDetected",      f"Blade {b} ice detection",                                       "bool",  "BOOL",  0, 1, cat, 5, True)
    add(f"{PREFIX}.ROT.B{b}.HeaterOn",         f"Blade {b} de-icing heater on",                                  "bool",  "BOOL",  0, 1, cat, 5)
    add(f"{PREFIX}.ROT.B{b}.LightningCount",   f"Blade {b} lightning strike counter",                            "count", "INT",   0, 10000, cat, 60)

# =========================================================
# 4) GEARBOX (50)
# =========================================================
cat = "Gearbox"
add(f"{PREFIX}.GBX.OilTemp_Sump",          "Gearbox sump oil temperature",                                       "°C",    "FLOAT", -20, 120, cat, 5, True)
add(f"{PREFIX}.GBX.OilTemp_Inlet",         "Gearbox oil inlet temperature",                                      "°C",    "FLOAT", -20, 120, cat, 5)
add(f"{PREFIX}.GBX.OilTemp_Outlet",        "Gearbox oil outlet temperature",                                     "°C",    "FLOAT", -20, 120, cat, 5)
add(f"{PREFIX}.GBX.OilPressure",           "Gearbox oil pressure",                                               "bar",   "FLOAT", 0, 20, cat, 1, True)
add(f"{PREFIX}.GBX.OilFlow",               "Gearbox oil flow",                                                   "L/min", "FLOAT", 0, 500, cat, 5)
add(f"{PREFIX}.GBX.OilLevel",              "Gearbox oil level",                                                  "%",     "FLOAT", 0, 100, cat, 30, True)
add(f"{PREFIX}.GBX.OilParticleCount",      "Oil particle contamination count",                                   "ppm",   "FLOAT", 0, 1000, cat, 60)
add(f"{PREFIX}.GBX.OilMoisture",           "Oil moisture content",                                               "ppm",   "FLOAT", 0, 500, cat, 60)
add(f"{PREFIX}.GBX.OilFilter_DiffPressure","Oil filter differential pressure",                                   "bar",   "FLOAT", 0, 10, cat, 5)
add(f"{PREFIX}.GBX.OilFilter_Clogged",     "Oil filter clogged warning",                                         "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.GBX.OilHeater_On",          "Oil heater active",                                                  "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.GBX.OilCooler_On",          "Oil cooler active",                                                  "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.GBX.OilPump_Running",       "Oil lubrication pump running",                                       "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.GBX.OilPump_Current",       "Oil pump motor current",                                             "A",     "FLOAT", 0, 50, cat, 5)
add(f"{PREFIX}.GBX.HSS_Speed",             "High-speed shaft (HSS) speed",                                       "rpm",   "FLOAT", 0, 2500, cat, 1, True)
add(f"{PREFIX}.GBX.HSS_Torque",            "HSS torque",                                                         "kNm",   "FLOAT", 0, 200, cat, 1)
add(f"{PREFIX}.GBX.HSS_Bearing_TempDE",    "HSS bearing temp drive end",                                         "°C",    "FLOAT", -20, 130, cat, 5, True)
add(f"{PREFIX}.GBX.HSS_Bearing_TempNDE",   "HSS bearing temp non-drive end",                                     "°C",    "FLOAT", -20, 130, cat, 5, True)
add(f"{PREFIX}.GBX.HSS_Bearing_Vibration", "HSS bearing vibration RMS",                                          "mm/s",  "FLOAT", 0, 50, cat, 1, True)
add(f"{PREFIX}.GBX.HSS_Bearing_VibPeak",   "HSS bearing vibration peak",                                         "mm/s",  "FLOAT", 0, 200, cat, 1)
add(f"{PREFIX}.GBX.HSS_Bearing_Envelope",  "HSS bearing envelope acceleration",                                  "g",     "FLOAT", 0, 10, cat, 1)
add(f"{PREFIX}.GBX.IMS_Speed",             "Intermediate-speed shaft (IMS) speed",                               "rpm",   "FLOAT", 0, 1000, cat, 1)
add(f"{PREFIX}.GBX.IMS_Bearing_TempDE",    "IMS bearing temp drive end",                                         "°C",    "FLOAT", -20, 130, cat, 5)
add(f"{PREFIX}.GBX.IMS_Bearing_TempNDE",   "IMS bearing temp non-drive end",                                     "°C",    "FLOAT", -20, 130, cat, 5)
add(f"{PREFIX}.GBX.IMS_Bearing_Vibration", "IMS bearing vibration RMS",                                          "mm/s",  "FLOAT", 0, 50, cat, 1)
add(f"{PREFIX}.GBX.LSS_Bearing_TempDE",    "Low-speed stage bearing temp DE",                                    "°C",    "FLOAT", -20, 130, cat, 5)
add(f"{PREFIX}.GBX.LSS_Bearing_TempNDE",   "Low-speed stage bearing temp NDE",                                   "°C",    "FLOAT", -20, 130, cat, 5)
add(f"{PREFIX}.GBX.LSS_Bearing_Vibration", "Low-speed stage bearing vibration",                                  "mm/s",  "FLOAT", 0, 50, cat, 1)
add(f"{PREFIX}.GBX.PlanetaryStage_Temp",   "Planetary stage temperature",                                        "°C",    "FLOAT", -20, 130, cat, 5)
add(f"{PREFIX}.GBX.PlanetaryStage_Vib",    "Planetary stage vibration",                                          "mm/s",  "FLOAT", 0, 50, cat, 1)
add(f"{PREFIX}.GBX.Housing_Temp",          "Gearbox housing temperature",                                        "°C",    "FLOAT", -20, 130, cat, 10)
add(f"{PREFIX}.GBX.Housing_Vibration",     "Gearbox housing vibration",                                          "mm/s",  "FLOAT", 0, 50, cat, 1)
add(f"{PREFIX}.GBX.RatioMeasured",         "Measured gear ratio",                                                "-",     "FLOAT", 1, 200, cat, 60)
add(f"{PREFIX}.GBX.RatioNominal",          "Nominal gear ratio",                                                 "-",     "FLOAT", 1, 200, cat, 3600)
add(f"{PREFIX}.GBX.SlipAlarm",             "Gear slip alarm",                                                    "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.GBX.RunHours",              "Gearbox cumulative run hours",                                       "h",     "FLOAT", 0, 1e6, cat, 60)
add(f"{PREFIX}.GBX.LoadCycleCount",        "Cumulative load cycle count",                                        "count", "INT",   0, 1e9, cat, 60)
add(f"{PREFIX}.GBX.OverloadEvents",        "Overload event count",                                               "count", "INT",   0, 10000, cat, 30)
add(f"{PREFIX}.GBX.OilChangeOverdueDays",  "Days overdue for oil change (negative = days left)",                 "d",     "INT",   -3650, 365, cat, 3600)
add(f"{PREFIX}.GBX.LubricationCycles",     "Auto-lubrication cycles count",                                      "count", "INT",   0, 1e6, cat, 60)
add(f"{PREFIX}.GBX.OilQualityIndex",       "Oil quality composite index 0-100",                                  "%",     "FLOAT", 0, 100, cat, 300)
add(f"{PREFIX}.GBX.AcousticEmission",      "Acoustic emission level",                                            "dB",    "FLOAT", 0, 150, cat, 5)
add(f"{PREFIX}.GBX.MagneticPlug_Status",   "Magnetic chip detector trigger",                                     "bool",  "BOOL",  0, 1, cat, 30, True)
add(f"{PREFIX}.GBX.CoolingFan1_Speed",     "Gearbox cooling fan 1 speed",                                        "rpm",   "FLOAT", 0, 3000, cat, 5)
add(f"{PREFIX}.GBX.CoolingFan2_Speed",     "Gearbox cooling fan 2 speed",                                        "rpm",   "FLOAT", 0, 3000, cat, 5)
add(f"{PREFIX}.GBX.CoolingFan1_Current",   "Gearbox cooling fan 1 current",                                      "A",     "FLOAT", 0, 30, cat, 5)
add(f"{PREFIX}.GBX.CoolingFan2_Current",   "Gearbox cooling fan 2 current",                                      "A",     "FLOAT", 0, 30, cat, 5)
add(f"{PREFIX}.GBX.OilHeaterCurrent",      "Oil heater current",                                                 "A",     "FLOAT", 0, 30, cat, 5)
add(f"{PREFIX}.GBX.PressureAlarm_Low",     "Low oil pressure alarm",                                             "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.GBX.TempAlarm_High",        "High oil temperature alarm",                                         "bool",  "BOOL",  0, 1, cat, 1, True)

# =========================================================
# 5) GENERATOR (55)
# =========================================================
cat = "Generator"
add(f"{PREFIX}.GENRT.Speed",               "Generator rotor speed",                                              "rpm",   "FLOAT", 0, 2500, cat, 1, True)
add(f"{PREFIX}.GENRT.Speed_SP",            "Generator speed setpoint",                                           "rpm",   "FLOAT", 0, 2500, cat, 1)
add(f"{PREFIX}.GENRT.Torque",              "Generator electromagnetic torque",                                   "kNm",   "FLOAT", -200, 200, cat, 1)
add(f"{PREFIX}.GENRT.Torque_SP",           "Generator torque setpoint",                                          "kNm",   "FLOAT", -200, 200, cat, 1)
add(f"{PREFIX}.GENRT.ActivePower",         "Generator active power output",                                      "kW",    "FLOAT", -500, 20000, cat, 1, True)
add(f"{PREFIX}.GENRT.ReactivePower",       "Generator reactive power",                                           "kvar",  "FLOAT", -10000, 10000, cat, 1)
add(f"{PREFIX}.GENRT.ApparentPower",       "Generator apparent power",                                           "kVA",   "FLOAT", 0, 25000, cat, 1)
add(f"{PREFIX}.GENRT.PowerFactor",         "Generator power factor",                                             "-",     "FLOAT", -1, 1, cat, 1)
add(f"{PREFIX}.GENRT.Frequency",           "Generator electrical frequency",                                     "Hz",    "FLOAT", 0, 100, cat, 1)
add(f"{PREFIX}.GENRT.SlipRatio",           "Generator slip (DFIG)",                                              "-",     "FLOAT", -0.5, 0.5, cat, 1)
# Stator
add(f"{PREFIX}.GENRT.Stator.Voltage_L1",   "Stator voltage L1",                                                  "V",     "FLOAT", 0, 1500, cat, 1)
add(f"{PREFIX}.GENRT.Stator.Voltage_L2",   "Stator voltage L2",                                                  "V",     "FLOAT", 0, 1500, cat, 1)
add(f"{PREFIX}.GENRT.Stator.Voltage_L3",   "Stator voltage L3",                                                  "V",     "FLOAT", 0, 1500, cat, 1)
add(f"{PREFIX}.GENRT.Stator.Current_L1",   "Stator current L1",                                                  "A",     "FLOAT", 0, 3000, cat, 1)
add(f"{PREFIX}.GENRT.Stator.Current_L2",   "Stator current L2",                                                  "A",     "FLOAT", 0, 3000, cat, 1)
add(f"{PREFIX}.GENRT.Stator.Current_L3",   "Stator current L3",                                                  "A",     "FLOAT", 0, 3000, cat, 1)
add(f"{PREFIX}.GENRT.Stator.Winding_Temp_U","Stator winding temperature phase U",                                "°C",    "FLOAT", -20, 200, cat, 5, True)
add(f"{PREFIX}.GENRT.Stator.Winding_Temp_V","Stator winding temperature phase V",                                "°C",    "FLOAT", -20, 200, cat, 5, True)
add(f"{PREFIX}.GENRT.Stator.Winding_Temp_W","Stator winding temperature phase W",                                "°C",    "FLOAT", -20, 200, cat, 5, True)
# Rotor (electrical)
add(f"{PREFIX}.GENRT.Rotor.Voltage_L1",    "Rotor voltage L1",                                                   "V",     "FLOAT", 0, 1500, cat, 1)
add(f"{PREFIX}.GENRT.Rotor.Voltage_L2",    "Rotor voltage L2",                                                   "V",     "FLOAT", 0, 1500, cat, 1)
add(f"{PREFIX}.GENRT.Rotor.Voltage_L3",    "Rotor voltage L3",                                                   "V",     "FLOAT", 0, 1500, cat, 1)
add(f"{PREFIX}.GENRT.Rotor.Current_L1",    "Rotor current L1",                                                   "A",     "FLOAT", 0, 3000, cat, 1)
add(f"{PREFIX}.GENRT.Rotor.Current_L2",    "Rotor current L2",                                                   "A",     "FLOAT", 0, 3000, cat, 1)
add(f"{PREFIX}.GENRT.Rotor.Current_L3",    "Rotor current L3",                                                   "A",     "FLOAT", 0, 3000, cat, 1)
add(f"{PREFIX}.GENRT.Rotor.Winding_Temp_U","Rotor winding temperature U",                                        "°C",    "FLOAT", -20, 200, cat, 5)
add(f"{PREFIX}.GENRT.Rotor.Winding_Temp_V","Rotor winding temperature V",                                        "°C",    "FLOAT", -20, 200, cat, 5)
add(f"{PREFIX}.GENRT.Rotor.Winding_Temp_W","Rotor winding temperature W",                                        "°C",    "FLOAT", -20, 200, cat, 5)
# Bearings
add(f"{PREFIX}.GENRT.Bearing_TempDE",      "Generator bearing temp drive end",                                   "°C",    "FLOAT", -20, 150, cat, 5, True)
add(f"{PREFIX}.GENRT.Bearing_TempNDE",     "Generator bearing temp non-drive end",                               "°C",    "FLOAT", -20, 150, cat, 5, True)
add(f"{PREFIX}.GENRT.Bearing_VibDE",       "Generator bearing vibration DE",                                     "mm/s",  "FLOAT", 0, 50, cat, 1)
add(f"{PREFIX}.GENRT.Bearing_VibNDE",      "Generator bearing vibration NDE",                                    "mm/s",  "FLOAT", 0, 50, cat, 1)
add(f"{PREFIX}.GENRT.Bearing_AxialVib",    "Generator axial vibration",                                          "mm/s",  "FLOAT", 0, 50, cat, 1)
add(f"{PREFIX}.GENRT.Bearing_GreasePressure","Bearing grease pressure",                                          "bar",   "FLOAT", 0, 30, cat, 30)
add(f"{PREFIX}.GENRT.Bearing_GreaseLevel", "Bearing grease level",                                               "%",     "FLOAT", 0, 100, cat, 60)
# Cooling
add(f"{PREFIX}.GENRT.CoolingFan1_Speed",   "Generator cooling fan 1 speed",                                      "rpm",   "FLOAT", 0, 3000, cat, 5)
add(f"{PREFIX}.GENRT.CoolingFan2_Speed",   "Generator cooling fan 2 speed",                                      "rpm",   "FLOAT", 0, 3000, cat, 5)
add(f"{PREFIX}.GENRT.CoolingAir_InletTemp","Cooling air inlet temperature",                                      "°C",    "FLOAT", -40, 80, cat, 5)
add(f"{PREFIX}.GENRT.CoolingAir_OutletTemp","Cooling air outlet temperature",                                    "°C",    "FLOAT", -40, 150, cat, 5)
add(f"{PREFIX}.GENRT.CoolingWater_Temp",   "Liquid cooling temperature (if applicable)",                         "°C",    "FLOAT", -40, 100, cat, 5)
add(f"{PREFIX}.GENRT.CoolingWater_Pressure","Liquid cooling pressure",                                           "bar",   "FLOAT", 0, 10, cat, 5)
add(f"{PREFIX}.GENRT.SlipRing_Temp",       "Slip ring temperature",                                              "°C",    "FLOAT", -20, 200, cat, 5)
add(f"{PREFIX}.GENRT.SlipRing_Wear",       "Slip ring brush wear",                                               "%",     "FLOAT", 0, 100, cat, 3600)
add(f"{PREFIX}.GENRT.InsulationResistance","Insulation resistance",                                              "MΩ",    "FLOAT", 0, 10000, cat, 3600)
add(f"{PREFIX}.GENRT.PartialDischarge",    "Partial discharge intensity",                                        "pC",    "FLOAT", 0, 10000, cat, 60)
add(f"{PREFIX}.GENRT.EnergyProduced_Today","Energy produced today",                                              "kWh",   "FLOAT", 0, 1e6, cat, 60)
add(f"{PREFIX}.GENRT.EnergyProduced_Month","Energy produced this month",                                         "kWh",   "FLOAT", 0, 1e8, cat, 300)
add(f"{PREFIX}.GENRT.EnergyProduced_Year", "Energy produced this year",                                          "kWh",   "FLOAT", 0, 1e9, cat, 300)
add(f"{PREFIX}.GENRT.EnergyProduced_Total","Energy produced lifetime",                                           "kWh",   "FLOAT", 0, 1e10, cat, 300)
add(f"{PREFIX}.GENRT.OverspeedTrips",      "Overspeed trip event count",                                         "count", "INT",   0, 10000, cat, 30, True)
add(f"{PREFIX}.GENRT.RunHours",            "Generator cumulative run hours",                                     "h",     "FLOAT", 0, 1e6, cat, 60)
add(f"{PREFIX}.GENRT.RatedSpeed",          "Generator rated speed",                                              "rpm",   "FLOAT", 0, 2500, cat, 3600)
add(f"{PREFIX}.GENRT.RatedPower",          "Generator rated power",                                              "kW",    "FLOAT", 0, 20000, cat, 3600)
add(f"{PREFIX}.GENRT.RatedCurrent",        "Generator rated current",                                            "A",     "FLOAT", 0, 5000, cat, 3600)
add(f"{PREFIX}.GENRT.SlipRing_Current",    "Slip ring current",                                                  "A",     "FLOAT", 0, 3000, cat, 1)

# =========================================================
# 6) CONVERTER (40)
# =========================================================
cat = "Converter"
add(f"{PREFIX}.CNV.GridSide.Voltage_L1",   "Grid-side converter voltage L1",                                     "V",     "FLOAT", 0, 1500, cat, 1)
add(f"{PREFIX}.CNV.GridSide.Voltage_L2",   "Grid-side converter voltage L2",                                     "V",     "FLOAT", 0, 1500, cat, 1)
add(f"{PREFIX}.CNV.GridSide.Voltage_L3",   "Grid-side converter voltage L3",                                     "V",     "FLOAT", 0, 1500, cat, 1)
add(f"{PREFIX}.CNV.GridSide.Current_L1",   "Grid-side converter current L1",                                     "A",     "FLOAT", 0, 3000, cat, 1)
add(f"{PREFIX}.CNV.GridSide.Current_L2",   "Grid-side converter current L2",                                     "A",     "FLOAT", 0, 3000, cat, 1)
add(f"{PREFIX}.CNV.GridSide.Current_L3",   "Grid-side converter current L3",                                     "A",     "FLOAT", 0, 3000, cat, 1)
add(f"{PREFIX}.CNV.GridSide.ActivePower",  "Grid-side active power",                                             "kW",    "FLOAT", -20000, 20000, cat, 1)
add(f"{PREFIX}.CNV.GridSide.ReactivePower","Grid-side reactive power",                                           "kvar",  "FLOAT", -10000, 10000, cat, 1)
add(f"{PREFIX}.CNV.GridSide.Frequency",    "Grid-side frequency",                                                "Hz",    "FLOAT", 0, 100, cat, 1)
add(f"{PREFIX}.CNV.GridSide.IGBT_Temp1",   "Grid-side IGBT temp 1",                                              "°C",    "FLOAT", -20, 150, cat, 1, True)
add(f"{PREFIX}.CNV.GridSide.IGBT_Temp2",   "Grid-side IGBT temp 2",                                              "°C",    "FLOAT", -20, 150, cat, 1, True)
add(f"{PREFIX}.CNV.GridSide.IGBT_Temp3",   "Grid-side IGBT temp 3",                                              "°C",    "FLOAT", -20, 150, cat, 1, True)
add(f"{PREFIX}.CNV.RotorSide.Voltage_L1",  "Rotor-side converter voltage L1",                                    "V",     "FLOAT", 0, 1500, cat, 1)
add(f"{PREFIX}.CNV.RotorSide.Voltage_L2",  "Rotor-side converter voltage L2",                                    "V",     "FLOAT", 0, 1500, cat, 1)
add(f"{PREFIX}.CNV.RotorSide.Voltage_L3",  "Rotor-side converter voltage L3",                                    "V",     "FLOAT", 0, 1500, cat, 1)
add(f"{PREFIX}.CNV.RotorSide.Current_L1",  "Rotor-side converter current L1",                                    "A",     "FLOAT", 0, 3000, cat, 1)
add(f"{PREFIX}.CNV.RotorSide.Current_L2",  "Rotor-side converter current L2",                                    "A",     "FLOAT", 0, 3000, cat, 1)
add(f"{PREFIX}.CNV.RotorSide.Current_L3",  "Rotor-side converter current L3",                                    "A",     "FLOAT", 0, 3000, cat, 1)
add(f"{PREFIX}.CNV.RotorSide.IGBT_Temp1",  "Rotor-side IGBT temp 1",                                             "°C",    "FLOAT", -20, 150, cat, 1, True)
add(f"{PREFIX}.CNV.RotorSide.IGBT_Temp2",  "Rotor-side IGBT temp 2",                                             "°C",    "FLOAT", -20, 150, cat, 1, True)
add(f"{PREFIX}.CNV.RotorSide.IGBT_Temp3",  "Rotor-side IGBT temp 3",                                             "°C",    "FLOAT", -20, 150, cat, 1, True)
add(f"{PREFIX}.CNV.DCLink.Voltage",        "DC link voltage",                                                    "V",     "FLOAT", 0, 2000, cat, 1, True)
add(f"{PREFIX}.CNV.DCLink.Voltage_SP",     "DC link voltage setpoint",                                           "V",     "FLOAT", 0, 2000, cat, 1)
add(f"{PREFIX}.CNV.DCLink.Current",        "DC link current",                                                    "A",     "FLOAT", -3000, 3000, cat, 1)
add(f"{PREFIX}.CNV.DCLink.Capacitor_Temp", "DC link capacitor temperature",                                      "°C",    "FLOAT", -20, 100, cat, 5)
add(f"{PREFIX}.CNV.DCLink.RippleVoltage",  "DC link voltage ripple",                                             "V",     "FLOAT", 0, 200, cat, 5)
add(f"{PREFIX}.CNV.ChopperResistor_Temp",  "Brake chopper resistor temperature",                                 "°C",    "FLOAT", -20, 400, cat, 5)
add(f"{PREFIX}.CNV.ChopperActive",         "Brake chopper active",                                               "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.CNV.CoolingFan_Speed",      "Converter cooling fan speed",                                        "rpm",   "FLOAT", 0, 5000, cat, 5)
add(f"{PREFIX}.CNV.CoolingFan_Current",    "Converter cooling fan current",                                      "A",     "FLOAT", 0, 30, cat, 5)
add(f"{PREFIX}.CNV.WaterCooling_InletTemp","Converter water cooling inlet temp",                                 "°C",    "FLOAT", -20, 80, cat, 5)
add(f"{PREFIX}.CNV.WaterCooling_OutletTemp","Converter water cooling outlet temp",                               "°C",    "FLOAT", -20, 100, cat, 5)
add(f"{PREFIX}.CNV.WaterCooling_Flow",     "Converter water cooling flow",                                       "L/min", "FLOAT", 0, 200, cat, 5)
add(f"{PREFIX}.CNV.WaterCooling_Pressure", "Converter water cooling pressure",                                   "bar",   "FLOAT", 0, 10, cat, 5)
add(f"{PREFIX}.CNV.CabinetTemp",           "Converter cabinet internal temp",                                    "°C",    "FLOAT", -20, 80, cat, 10)
add(f"{PREFIX}.CNV.CabinetHumidity",       "Converter cabinet humidity",                                         "%",     "FLOAT", 0, 100, cat, 30)
add(f"{PREFIX}.CNV.Efficiency",            "Converter efficiency",                                               "%",     "FLOAT", 0, 100, cat, 10)
add(f"{PREFIX}.CNV.SwitchingFrequency",    "PWM switching frequency",                                            "Hz",    "FLOAT", 0, 10000, cat, 10)
add(f"{PREFIX}.CNV.OverloadCounter",       "Converter overload count",                                           "count", "INT",   0, 10000, cat, 30)
add(f"{PREFIX}.CNV.FaultCode",             "Converter active fault code",                                        "code",  "INT",   0, 9999, cat, 1)

# =========================================================
# 7) TRANSFORMER (25)
# =========================================================
cat = "Transformer"
add(f"{PREFIX}.TRF.OilTemp_Top",           "Transformer oil top temperature",                                    "°C",    "FLOAT", -20, 150, cat, 5, True)
add(f"{PREFIX}.TRF.OilTemp_Bottom",        "Transformer oil bottom temperature",                                 "°C",    "FLOAT", -20, 150, cat, 5)
add(f"{PREFIX}.TRF.WindingTemp_HV_U",      "HV winding temperature U",                                           "°C",    "FLOAT", -20, 180, cat, 5, True)
add(f"{PREFIX}.TRF.WindingTemp_HV_V",      "HV winding temperature V",                                           "°C",    "FLOAT", -20, 180, cat, 5, True)
add(f"{PREFIX}.TRF.WindingTemp_HV_W",      "HV winding temperature W",                                           "°C",    "FLOAT", -20, 180, cat, 5, True)
add(f"{PREFIX}.TRF.WindingTemp_LV_U",      "LV winding temperature U",                                           "°C",    "FLOAT", -20, 180, cat, 5)
add(f"{PREFIX}.TRF.WindingTemp_LV_V",      "LV winding temperature V",                                           "°C",    "FLOAT", -20, 180, cat, 5)
add(f"{PREFIX}.TRF.WindingTemp_LV_W",      "LV winding temperature W",                                           "°C",    "FLOAT", -20, 180, cat, 5)
add(f"{PREFIX}.TRF.HV.Voltage_L1",         "HV side voltage L1",                                                 "V",     "FLOAT", 0, 50000, cat, 1)
add(f"{PREFIX}.TRF.HV.Voltage_L2",         "HV side voltage L2",                                                 "V",     "FLOAT", 0, 50000, cat, 1)
add(f"{PREFIX}.TRF.HV.Voltage_L3",         "HV side voltage L3",                                                 "V",     "FLOAT", 0, 50000, cat, 1)
add(f"{PREFIX}.TRF.HV.Current_L1",         "HV side current L1",                                                 "A",     "FLOAT", 0, 1000, cat, 1)
add(f"{PREFIX}.TRF.HV.Current_L2",         "HV side current L2",                                                 "A",     "FLOAT", 0, 1000, cat, 1)
add(f"{PREFIX}.TRF.HV.Current_L3",         "HV side current L3",                                                 "A",     "FLOAT", 0, 1000, cat, 1)
add(f"{PREFIX}.TRF.OilLevel",              "Transformer oil level",                                              "%",     "FLOAT", 0, 100, cat, 60, True)
add(f"{PREFIX}.TRF.OilPressure",           "Transformer oil pressure",                                           "bar",   "FLOAT", 0, 5, cat, 30)
add(f"{PREFIX}.TRF.BuchholzAlarm",         "Buchholz relay alarm",                                               "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.TRF.BuchholzTrip",          "Buchholz relay trip",                                                "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.TRF.PressureRelief",        "Pressure relief device triggered",                                   "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.TRF.TapPosition",           "On-load tap-changer position",                                       "step",  "INT",   1, 25, cat, 60)
add(f"{PREFIX}.TRF.CoolingFan_Status",     "Transformer cooling fan running",                                    "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.TRF.Load",                  "Transformer load",                                                   "%",     "FLOAT", 0, 150, cat, 5)
add(f"{PREFIX}.TRF.Efficiency",            "Transformer efficiency",                                             "%",     "FLOAT", 0, 100, cat, 60)
add(f"{PREFIX}.TRF.MoistureContent",       "Oil moisture content",                                               "ppm",   "FLOAT", 0, 100, cat, 3600)
add(f"{PREFIX}.TRF.DissolvedGasH2",        "Dissolved gas H2 in oil",                                            "ppm",   "FLOAT", 0, 10000, cat, 3600)

# =========================================================
# 8) YAW SYSTEM (25)
# =========================================================
cat = "Yaw"
add(f"{PREFIX}.YAW.NacellePosition",       "Absolute nacelle position",                                          "deg",   "FLOAT", 0, 360, cat, 1, True)
add(f"{PREFIX}.YAW.NacellePosition_SP",    "Nacelle position setpoint",                                          "deg",   "FLOAT", 0, 360, cat, 1)
add(f"{PREFIX}.YAW.YawRate",               "Yaw rate",                                                           "deg/s", "FLOAT", -3, 3, cat, 1)
add(f"{PREFIX}.YAW.YawError",              "Yaw misalignment from wind",                                         "deg",   "FLOAT", -180, 180, cat, 1)
add(f"{PREFIX}.YAW.CableTwistAngle",       "Cable twist angle",                                                  "deg",   "FLOAT", -1080, 1080, cat, 5, True)
add(f"{PREFIX}.YAW.CableTwistDirection",   "Cable twist direction (1=CW,-1=CCW)",                                "-",     "INT",   -1, 1, cat, 5)
add(f"{PREFIX}.YAW.UntwistRequest",        "Auto-untwist requested",                                             "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.YAW.Motor1_Current",        "Yaw motor 1 current",                                                "A",     "FLOAT", 0, 100, cat, 1)
add(f"{PREFIX}.YAW.Motor2_Current",        "Yaw motor 2 current",                                                "A",     "FLOAT", 0, 100, cat, 1)
add(f"{PREFIX}.YAW.Motor3_Current",        "Yaw motor 3 current",                                                "A",     "FLOAT", 0, 100, cat, 1)
add(f"{PREFIX}.YAW.Motor4_Current",        "Yaw motor 4 current",                                                "A",     "FLOAT", 0, 100, cat, 1)
add(f"{PREFIX}.YAW.Motor1_Temp",           "Yaw motor 1 temperature",                                            "°C",    "FLOAT", -20, 150, cat, 5)
add(f"{PREFIX}.YAW.Motor2_Temp",           "Yaw motor 2 temperature",                                            "°C",    "FLOAT", -20, 150, cat, 5)
add(f"{PREFIX}.YAW.Motor3_Temp",           "Yaw motor 3 temperature",                                            "°C",    "FLOAT", -20, 150, cat, 5)
add(f"{PREFIX}.YAW.Motor4_Temp",           "Yaw motor 4 temperature",                                            "°C",    "FLOAT", -20, 150, cat, 5)
add(f"{PREFIX}.YAW.Brake_Pressure",        "Yaw brake hydraulic pressure",                                       "bar",   "FLOAT", 0, 250, cat, 5)
add(f"{PREFIX}.YAW.Brake_Released",        "Yaw brake released",                                                 "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.YAW.Brake_PadWear",         "Yaw brake pad wear",                                                 "%",     "FLOAT", 0, 100, cat, 3600)
add(f"{PREFIX}.YAW.Gear_OilTemp",          "Yaw gear oil temperature",                                           "°C",    "FLOAT", -20, 130, cat, 30)
add(f"{PREFIX}.YAW.Bearing_Temp",          "Yaw bearing temperature",                                            "°C",    "FLOAT", -20, 130, cat, 30)
add(f"{PREFIX}.YAW.Bearing_GreaseLevel",   "Yaw bearing grease level",                                           "%",     "FLOAT", 0, 100, cat, 3600)
add(f"{PREFIX}.YAW.YawCycles_Today",       "Yaw cycles today",                                                   "count", "INT",   0, 10000, cat, 60)
add(f"{PREFIX}.YAW.YawCycles_Total",       "Yaw cycles cumulative",                                              "count", "INT",   0, 1e9, cat, 300)
add(f"{PREFIX}.YAW.YawMoving",             "Yaw drive in motion",                                                "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.YAW.YawLocked",             "Yaw locked (storm/maintenance)",                                     "bool",  "BOOL",  0, 1, cat, 1)

# =========================================================
# 9) HYDRAULIC SYSTEM (25)
# =========================================================
cat = "Hydraulic"
add(f"{PREFIX}.HYD.SystemPressure",        "Hydraulic system pressure",                                          "bar",   "FLOAT", 0, 300, cat, 1, True)
add(f"{PREFIX}.HYD.AccumulatorPressure",   "Accumulator pressure",                                               "bar",   "FLOAT", 0, 300, cat, 5)
add(f"{PREFIX}.HYD.OilTemp",               "Hydraulic oil temperature",                                          "°C",    "FLOAT", -20, 120, cat, 5)
add(f"{PREFIX}.HYD.OilLevel",              "Hydraulic oil level",                                                "%",     "FLOAT", 0, 100, cat, 30, True)
add(f"{PREFIX}.HYD.OilFilter_DiffPressure","Hydraulic filter differential pressure",                             "bar",   "FLOAT", 0, 10, cat, 5)
add(f"{PREFIX}.HYD.OilFilter_Clogged",     "Hydraulic filter clogged",                                           "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.HYD.Pump1_Running",         "Hydraulic pump 1 running",                                           "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.HYD.Pump2_Running",         "Hydraulic pump 2 running",                                           "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.HYD.Pump1_Current",         "Hydraulic pump 1 motor current",                                     "A",     "FLOAT", 0, 50, cat, 5)
add(f"{PREFIX}.HYD.Pump2_Current",         "Hydraulic pump 2 motor current",                                     "A",     "FLOAT", 0, 50, cat, 5)
add(f"{PREFIX}.HYD.Pump1_RunHours",        "Hydraulic pump 1 run hours",                                         "h",     "FLOAT", 0, 1e6, cat, 60)
add(f"{PREFIX}.HYD.Pump2_RunHours",        "Hydraulic pump 2 run hours",                                         "h",     "FLOAT", 0, 1e6, cat, 60)
add(f"{PREFIX}.HYD.Pump1_Starts",          "Hydraulic pump 1 start count",                                       "count", "INT",   0, 1e6, cat, 60)
add(f"{PREFIX}.HYD.Pump2_Starts",          "Hydraulic pump 2 start count",                                        "count", "INT",   0, 1e6, cat, 60)
add(f"{PREFIX}.HYD.Valve1_Position",       "Hydraulic valve 1 position",                                         "%",     "FLOAT", 0, 100, cat, 1)
add(f"{PREFIX}.HYD.Valve2_Position",       "Hydraulic valve 2 position",                                         "%",     "FLOAT", 0, 100, cat, 1)
add(f"{PREFIX}.HYD.Valve3_Position",       "Hydraulic valve 3 position",                                         "%",     "FLOAT", 0, 100, cat, 1)
add(f"{PREFIX}.HYD.LeakDetected",          "Hydraulic leak detected",                                            "bool",  "BOOL",  0, 1, cat, 5, True)
add(f"{PREFIX}.HYD.OilParticleCount",      "Hydraulic oil particle count",                                       "ppm",   "FLOAT", 0, 1000, cat, 300)
add(f"{PREFIX}.HYD.OilMoisture",           "Hydraulic oil moisture",                                             "ppm",   "FLOAT", 0, 500, cat, 300)
add(f"{PREFIX}.HYD.HeaterOn",              "Hydraulic oil heater on",                                            "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.HYD.CoolerOn",              "Hydraulic oil cooler on",                                            "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.HYD.PressureAlarm_Low",     "Low hydraulic pressure alarm",                                       "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.HYD.PressureAlarm_High",    "High hydraulic pressure alarm",                                      "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.HYD.OilQualityIndex",       "Hydraulic oil quality index 0-100",                                  "%",     "FLOAT", 0, 100, cat, 3600)

# =========================================================
# 10) COOLING SYSTEM (25)
# =========================================================
cat = "Cooling"
add(f"{PREFIX}.COOL.AmbientFan1_Speed",    "Nacelle vent fan 1 speed",                                           "rpm",   "FLOAT", 0, 3000, cat, 5)
add(f"{PREFIX}.COOL.AmbientFan2_Speed",    "Nacelle vent fan 2 speed",                                           "rpm",   "FLOAT", 0, 3000, cat, 5)
add(f"{PREFIX}.COOL.AmbientFan1_Current",  "Nacelle vent fan 1 current",                                         "A",     "FLOAT", 0, 30, cat, 5)
add(f"{PREFIX}.COOL.AmbientFan2_Current",  "Nacelle vent fan 2 current",                                         "A",     "FLOAT", 0, 30, cat, 5)
add(f"{PREFIX}.COOL.NacelleAirTemp",       "Nacelle internal air temperature",                                   "°C",    "FLOAT", -40, 80, cat, 10)
add(f"{PREFIX}.COOL.NacelleAirHumidity",   "Nacelle internal humidity",                                          "%",     "FLOAT", 0, 100, cat, 30)
add(f"{PREFIX}.COOL.HeatExchanger_InletTemp","Heat exchanger inlet temperature",                                 "°C",    "FLOAT", -20, 100, cat, 5)
add(f"{PREFIX}.COOL.HeatExchanger_OutletTemp","Heat exchanger outlet temperature",                               "°C",    "FLOAT", -20, 100, cat, 5)
add(f"{PREFIX}.COOL.CoolantPump_Running",  "Coolant pump running",                                               "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.COOL.CoolantPump_Current",  "Coolant pump current",                                               "A",     "FLOAT", 0, 50, cat, 5)
add(f"{PREFIX}.COOL.CoolantFlow",          "Coolant flow rate",                                                  "L/min", "FLOAT", 0, 500, cat, 5)
add(f"{PREFIX}.COOL.CoolantPressure",      "Coolant loop pressure",                                              "bar",   "FLOAT", 0, 10, cat, 5)
add(f"{PREFIX}.COOL.CoolantLevel",         "Coolant reservoir level",                                            "%",     "FLOAT", 0, 100, cat, 60)
add(f"{PREFIX}.COOL.CoolantTemp",          "Coolant temperature",                                                "°C",    "FLOAT", -40, 120, cat, 5)
add(f"{PREFIX}.COOL.GlycolConcentration",  "Coolant glycol concentration",                                       "%",     "FLOAT", 0, 100, cat, 3600)
add(f"{PREFIX}.COOL.RadiatorFan1_Speed",   "Radiator fan 1 speed",                                               "rpm",   "FLOAT", 0, 3000, cat, 5)
add(f"{PREFIX}.COOL.RadiatorFan2_Speed",   "Radiator fan 2 speed",                                               "rpm",   "FLOAT", 0, 3000, cat, 5)
add(f"{PREFIX}.COOL.RadiatorFan3_Speed",   "Radiator fan 3 speed",                                               "rpm",   "FLOAT", 0, 3000, cat, 5)
add(f"{PREFIX}.COOL.RadiatorFan4_Speed",   "Radiator fan 4 speed",                                               "rpm",   "FLOAT", 0, 3000, cat, 5)
add(f"{PREFIX}.COOL.AirIntakeFilter_DP",   "Air intake filter pressure drop",                                    "Pa",    "FLOAT", 0, 5000, cat, 30)
add(f"{PREFIX}.COOL.AirIntakeFilter_Clogged","Air intake filter clogged",                                        "bool",  "BOOL",  0, 1, cat, 30)
add(f"{PREFIX}.COOL.TempControl_SP",       "Cooling system setpoint",                                            "°C",    "FLOAT", 0, 100, cat, 30)
add(f"{PREFIX}.COOL.EmergencyVent_Open",   "Emergency vent louver open",                                         "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.COOL.CoolingDemand",        "Cooling demand 0-100",                                               "%",     "FLOAT", 0, 100, cat, 5)
add(f"{PREFIX}.COOL.AlarmActive",          "Cooling system alarm active",                                        "bool",  "BOOL",  0, 1, cat, 1, True)

# =========================================================
# 11) BRAKE SYSTEM (20)
# =========================================================
cat = "Brake"
add(f"{PREFIX}.BRK.MechBrake_Pressure",    "Mechanical brake hydraulic pressure",                                "bar",   "FLOAT", 0, 250, cat, 1, True)
add(f"{PREFIX}.BRK.MechBrake_Applied",     "Mechanical brake applied",                                           "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.BRK.MechBrake_Released",    "Mechanical brake released",                                          "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.BRK.MechBrake_Temp",        "Mechanical brake disc temperature",                                  "°C",    "FLOAT", -20, 400, cat, 1, True)
add(f"{PREFIX}.BRK.MechBrake_PadWear1",    "Mech brake pad 1 wear",                                              "%",     "FLOAT", 0, 100, cat, 3600)
add(f"{PREFIX}.BRK.MechBrake_PadWear2",    "Mech brake pad 2 wear",                                              "%",     "FLOAT", 0, 100, cat, 3600)
add(f"{PREFIX}.BRK.MechBrake_Cycles",      "Mech brake cycle count",                                             "count", "INT",   0, 1e6, cat, 60)
add(f"{PREFIX}.BRK.MechBrake_EmergencyApplied","Emergency brake applied",                                        "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.BRK.ParkingBrake_Applied",  "Parking brake applied",                                              "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.BRK.AeroBrake_Active",      "Aerodynamic brake (pitch-to-feather) active",                        "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.BRK.AeroBrake_Cycles",      "Aerodynamic brake cycle count",                                      "count", "INT",   0, 1e6, cat, 60)
add(f"{PREFIX}.BRK.BrakeTime_Last",        "Time taken for last brake event",                                    "s",     "FLOAT", 0, 60, cat, 60)
add(f"{PREFIX}.BRK.BrakeForce_Last",       "Force during last brake event",                                      "kN",    "FLOAT", 0, 500, cat, 60)
add(f"{PREFIX}.BRK.BrakeCommand",          "Brake command from controller",                                      "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.BRK.BrakeFault",            "Brake system fault",                                                 "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.BRK.BrakeAccumulator_Pressure","Brake accumulator pressure",                                      "bar",   "FLOAT", 0, 250, cat, 5)
add(f"{PREFIX}.BRK.BrakeProximitySensor1", "Brake proximity sensor 1",                                           "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.BRK.BrakeProximitySensor2", "Brake proximity sensor 2",                                           "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.BRK.RotorLocked",           "Rotor lock pin engaged",                                             "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.BRK.RotorLockPinPosition",  "Rotor lock pin position",                                            "mm",    "FLOAT", 0, 500, cat, 5)

# =========================================================
# 12) LUBRICATION (20)
# =========================================================
cat = "Lubrication"
add(f"{PREFIX}.LUB.MainBearing_OilLevel",  "Main bearing lubrication reservoir level",                           "%",     "FLOAT", 0, 100, cat, 60)
add(f"{PREFIX}.LUB.MainBearing_GreaseLevel","Main bearing grease reservoir level",                               "%",     "FLOAT", 0, 100, cat, 60, True)
add(f"{PREFIX}.LUB.MainBearing_PumpRunning","Main bearing lube pump running",                                    "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.LUB.MainBearing_Cycles",    "Main bearing auto-lube cycles",                                      "count", "INT",   0, 1e6, cat, 60)
add(f"{PREFIX}.LUB.Generator_GreaseLevel", "Generator bearing grease level",                                     "%",     "FLOAT", 0, 100, cat, 60, True)
add(f"{PREFIX}.LUB.Generator_PumpRunning", "Generator lube pump running",                                        "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.LUB.Generator_Cycles",      "Generator auto-lube cycles",                                         "count", "INT",   0, 1e6, cat, 60)
add(f"{PREFIX}.LUB.Yaw_GreaseLevel",       "Yaw lubrication grease level",                                       "%",     "FLOAT", 0, 100, cat, 60)
add(f"{PREFIX}.LUB.Yaw_PumpRunning",       "Yaw lube pump running",                                              "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.LUB.Yaw_Cycles",            "Yaw auto-lube cycles",                                               "count", "INT",   0, 1e6, cat, 60)
add(f"{PREFIX}.LUB.Pitch_GreaseLevel",     "Pitch lubrication grease level",                                     "%",     "FLOAT", 0, 100, cat, 60)
add(f"{PREFIX}.LUB.Pitch_PumpRunning",     "Pitch lube pump running",                                            "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.LUB.Pitch_Cycles",          "Pitch auto-lube cycles",                                             "count", "INT",   0, 1e6, cat, 60)
add(f"{PREFIX}.LUB.OilUsage_Today",        "Lube oil consumed today",                                            "L",     "FLOAT", 0, 1000, cat, 300)
add(f"{PREFIX}.LUB.GreaseUsage_Today",     "Lube grease consumed today",                                         "kg",    "FLOAT", 0, 100, cat, 300)
add(f"{PREFIX}.LUB.PumpPressure",          "Central lubrication pump pressure",                                  "bar",   "FLOAT", 0, 350, cat, 5)
add(f"{PREFIX}.LUB.LowLevelAlarm",         "Low lubricant level alarm",                                          "bool",  "BOOL",  0, 1, cat, 5, True)
add(f"{PREFIX}.LUB.BlockedLineAlarm",      "Blocked lubrication line alarm",                                     "bool",  "BOOL",  0, 1, cat, 5, True)
add(f"{PREFIX}.LUB.NextServiceDue_Hours",  "Hours until next lube service",                                      "h",     "FLOAT", -1000, 10000, cat, 3600)
add(f"{PREFIX}.LUB.SystemFault",           "Lube system fault active",                                           "bool",  "BOOL",  0, 1, cat, 5, True)

# =========================================================
# 13) TOWER & STRUCTURAL (25)
# =========================================================
cat = "Tower"
add(f"{PREFIX}.TOW.Vibration_X_Top",       "Tower top vibration X-axis",                                         "mm/s",  "FLOAT", 0, 100, cat, 1, True)
add(f"{PREFIX}.TOW.Vibration_Y_Top",       "Tower top vibration Y-axis",                                         "mm/s",  "FLOAT", 0, 100, cat, 1, True)
add(f"{PREFIX}.TOW.Vibration_X_Peak",      "Tower top peak X vibration (10-min)",                                "mm/s",  "FLOAT", 0, 200, cat, 60)
add(f"{PREFIX}.TOW.Vibration_Y_Peak",      "Tower top peak Y vibration (10-min)",                                "mm/s",  "FLOAT", 0, 200, cat, 60)
add(f"{PREFIX}.TOW.Accel_X",               "Tower acceleration X",                                               "m/s^2", "FLOAT", -10, 10, cat, 1)
add(f"{PREFIX}.TOW.Accel_Y",               "Tower acceleration Y",                                               "m/s^2", "FLOAT", -10, 10, cat, 1)
add(f"{PREFIX}.TOW.Tilt_X",                "Tower tilt X",                                                       "deg",   "FLOAT", -5, 5, cat, 10)
add(f"{PREFIX}.TOW.Tilt_Y",                "Tower tilt Y",                                                       "deg",   "FLOAT", -5, 5, cat, 10)
add(f"{PREFIX}.TOW.BaseTemp",              "Tower base internal temperature",                                    "°C",    "FLOAT", -40, 80, cat, 60)
add(f"{PREFIX}.TOW.MidTemp",               "Tower mid-section internal temperature",                             "°C",    "FLOAT", -40, 80, cat, 60)
add(f"{PREFIX}.TOW.TopTemp",               "Tower top internal temperature",                                     "°C",    "FLOAT", -40, 80, cat, 60)
add(f"{PREFIX}.TOW.BaseHumidity",          "Tower base humidity",                                                "%",     "FLOAT", 0, 100, cat, 60)
add(f"{PREFIX}.TOW.DoorOpen_Base",         "Tower base door open",                                               "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.TOW.DoorOpen_Nacelle",      "Nacelle access hatch open",                                          "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.TOW.PersonInTower",         "Personnel detected in tower",                                        "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.TOW.ElevatorStatus",        "Service lift status (0=idle,1=moving,2=fault)",                      "code",  "INT",   0, 5, cat, 1)
add(f"{PREFIX}.TOW.ElevatorFloor",         "Service lift current floor",                                         "level", "INT",   0, 10, cat, 1)
add(f"{PREFIX}.TOW.FoundationStrainGauge1","Foundation strain gauge 1",                                          "µε",    "FLOAT", -500, 500, cat, 60)
add(f"{PREFIX}.TOW.FoundationStrainGauge2","Foundation strain gauge 2",                                          "µε",    "FLOAT", -500, 500, cat, 60)
add(f"{PREFIX}.TOW.FoundationTilt",        "Foundation tilt sensor",                                             "deg",   "FLOAT", -2, 2, cat, 60)
add(f"{PREFIX}.TOW.NaturalFrequency",      "Measured tower natural frequency",                                   "Hz",    "FLOAT", 0, 5, cat, 300)
add(f"{PREFIX}.TOW.WaterLeakDetected",     "Water leak detected at tower base",                                  "bool",  "BOOL",  0, 1, cat, 30)
add(f"{PREFIX}.TOW.BoltTensionAlarm",      "Tower bolt tension alarm",                                           "bool",  "BOOL",  0, 1, cat, 300, True)
add(f"{PREFIX}.TOW.LightningStrike_Tower", "Tower lightning strike count",                                       "count", "INT",   0, 1000, cat, 300)
add(f"{PREFIX}.TOW.ObstructionLightOn",    "Aviation obstruction light on",                                      "bool",  "BOOL",  0, 1, cat, 10)

# =========================================================
# 14) GRID CONNECTION (35)
# =========================================================
cat = "Grid"
add(f"{PREFIX}.GRID.Voltage_L1",           "Grid PCC voltage L1",                                                "V",     "FLOAT", 0, 50000, cat, 1, True)
add(f"{PREFIX}.GRID.Voltage_L2",           "Grid PCC voltage L2",                                                "V",     "FLOAT", 0, 50000, cat, 1, True)
add(f"{PREFIX}.GRID.Voltage_L3",           "Grid PCC voltage L3",                                                "V",     "FLOAT", 0, 50000, cat, 1, True)
add(f"{PREFIX}.GRID.Voltage_Avg",          "Grid average phase voltage",                                         "V",     "FLOAT", 0, 50000, cat, 1)
add(f"{PREFIX}.GRID.Voltage_Unbalance",    "Grid voltage unbalance",                                             "%",     "FLOAT", 0, 20, cat, 1)
add(f"{PREFIX}.GRID.Current_L1",           "Grid current L1",                                                    "A",     "FLOAT", 0, 1000, cat, 1)
add(f"{PREFIX}.GRID.Current_L2",           "Grid current L2",                                                    "A",     "FLOAT", 0, 1000, cat, 1)
add(f"{PREFIX}.GRID.Current_L3",           "Grid current L3",                                                    "A",     "FLOAT", 0, 1000, cat, 1)
add(f"{PREFIX}.GRID.Current_Avg",          "Grid average phase current",                                         "A",     "FLOAT", 0, 1000, cat, 1)
add(f"{PREFIX}.GRID.Frequency",            "Grid frequency",                                                     "Hz",    "FLOAT", 40, 70, cat, 1, True)
add(f"{PREFIX}.GRID.ActivePower",          "Grid active power export",                                           "kW",    "FLOAT", -500, 20000, cat, 1, True)
add(f"{PREFIX}.GRID.ReactivePower",        "Grid reactive power",                                                "kvar",  "FLOAT", -10000, 10000, cat, 1)
add(f"{PREFIX}.GRID.ApparentPower",        "Grid apparent power",                                                "kVA",   "FLOAT", 0, 25000, cat, 1)
add(f"{PREFIX}.GRID.PowerFactor",          "Grid power factor",                                                  "-",     "FLOAT", -1, 1, cat, 1)
add(f"{PREFIX}.GRID.ActivePower_SP",       "Active power setpoint from grid operator",                           "kW",    "FLOAT", 0, 20000, cat, 5)
add(f"{PREFIX}.GRID.ReactivePower_SP",     "Reactive power setpoint",                                            "kvar",  "FLOAT", -10000, 10000, cat, 5)
add(f"{PREFIX}.GRID.PowerFactor_SP",       "Power factor setpoint",                                              "-",     "FLOAT", -1, 1, cat, 5)
add(f"{PREFIX}.GRID.VoltageTHD",           "Voltage total harmonic distortion",                                  "%",     "FLOAT", 0, 30, cat, 5)
add(f"{PREFIX}.GRID.CurrentTHD",           "Current total harmonic distortion",                                  "%",     "FLOAT", 0, 30, cat, 5)
add(f"{PREFIX}.GRID.Harmonic_V_2",         "2nd harmonic voltage",                                               "%",     "FLOAT", 0, 30, cat, 30)
add(f"{PREFIX}.GRID.Harmonic_V_3",         "3rd harmonic voltage",                                               "%",     "FLOAT", 0, 30, cat, 30)
add(f"{PREFIX}.GRID.Harmonic_V_5",         "5th harmonic voltage",                                               "%",     "FLOAT", 0, 30, cat, 30)
add(f"{PREFIX}.GRID.Harmonic_V_7",         "7th harmonic voltage",                                               "%",     "FLOAT", 0, 30, cat, 30)
add(f"{PREFIX}.GRID.LVRT_Active",          "Low-voltage ride-through event active",                              "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.GRID.HVRT_Active",          "High-voltage ride-through event active",                             "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.GRID.FaultRideThrough_Count","FRT event count total",                                             "count", "INT",   0, 10000, cat, 60)
add(f"{PREFIX}.GRID.IslandingDetected",    "Anti-islanding detected",                                            "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.GRID.CircuitBreakerClosed", "Grid breaker closed",                                                "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.GRID.CircuitBreaker_Trips", "Grid breaker trip count",                                            "count", "INT",   0, 10000, cat, 30)
add(f"{PREFIX}.GRID.SyncStatus",           "Grid synchronization status",                                        "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.GRID.SyncErrorAngle",       "Phase angle error during sync",                                      "deg",   "FLOAT", -180, 180, cat, 1)
add(f"{PREFIX}.GRID.EnergyExport_Today",   "Energy exported to grid today",                                      "kWh",   "FLOAT", 0, 1e6, cat, 60)
add(f"{PREFIX}.GRID.EnergyImport_Today",   "Energy imported from grid today (aux)",                              "kWh",   "FLOAT", 0, 1e5, cat, 60)
add(f"{PREFIX}.GRID.EnergyExport_Total",   "Energy exported lifetime",                                           "kWh",   "FLOAT", 0, 1e10, cat, 300)
add(f"{PREFIX}.GRID.PCCImpedance",         "Estimated PCC short-circuit impedance",                              "Ω",     "FLOAT", 0, 100, cat, 3600)

# =========================================================
# 15) SAFETY SYSTEMS (20)
# =========================================================
cat = "Safety"
add(f"{PREFIX}.SAFE.EmergencyStop_Active", "Any e-stop button pressed",                                          "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.SAFE.EmergencyStop_Tower",  "Tower base e-stop pressed",                                          "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.SAFE.EmergencyStop_Nacelle","Nacelle e-stop pressed",                                             "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.SAFE.EmergencyStop_Hub",    "Hub e-stop pressed",                                                 "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.SAFE.SafetyChainOK",        "Safety chain closed (all relays OK)",                                "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.SAFE.Overspeed_Active",     "Overspeed detected",                                                 "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.SAFE.OverVibration_Active", "Excessive vibration detected",                                       "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.SAFE.FireDetected",         "Fire detection alarm",                                               "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.SAFE.SmokeDetected",        "Smoke detected",                                                     "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.SAFE.FireSuppressionDischarged","Fire suppression discharged",                                    "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.SAFE.HeatDetected",         "Heat detector alarm",                                                "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.SAFE.GasDetected",          "Combustible gas detected",                                           "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.SAFE.ArcFlash_Detected",    "Arc flash detected",                                                 "bool",  "BOOL",  0, 1, cat, 1, True)
add(f"{PREFIX}.SAFE.IceLoadAlarm",         "Excessive ice load on rotor",                                        "bool",  "BOOL",  0, 1, cat, 5, True)
add(f"{PREFIX}.SAFE.StormShutdown",        "Storm shutdown active",                                              "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.SAFE.GridLossShutdown",     "Grid loss shutdown active",                                          "bool",  "BOOL",  0, 1, cat, 1)
add(f"{PREFIX}.SAFE.UPS_OnBattery",        "UPS running on battery",                                             "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.SAFE.UPS_BatteryLevel",     "UPS battery state of charge",                                        "%",     "FLOAT", 0, 100, cat, 30)
add(f"{PREFIX}.SAFE.LockoutTagout_Active", "LOTO active for maintenance",                                        "bool",  "BOOL",  0, 1, cat, 5)
add(f"{PREFIX}.SAFE.WatchdogFault",        "Controller watchdog timeout",                                        "bool",  "BOOL",  0, 1, cat, 1, True)

# =========================================================
# 16) POWER PERFORMANCE / KPIs (20)
# =========================================================
cat = "Performance"
add(f"{PREFIX}.PERF.CapacityFactor_Today", "Capacity factor today",                                              "%",     "FLOAT", 0, 100, cat, 60)
add(f"{PREFIX}.PERF.CapacityFactor_Month", "Capacity factor month-to-date",                                      "%",     "FLOAT", 0, 100, cat, 300)
add(f"{PREFIX}.PERF.CapacityFactor_Year",  "Capacity factor year-to-date",                                       "%",     "FLOAT", 0, 100, cat, 300)
add(f"{PREFIX}.PERF.MTBF",                 "Mean time between failures",                                         "h",     "FLOAT", 0, 1e6, cat, 3600)
add(f"{PREFIX}.PERF.MTTR",                 "Mean time to repair",                                                "h",     "FLOAT", 0, 1000, cat, 3600)
add(f"{PREFIX}.PERF.PowerCurveDeviation",  "Deviation from theoretical power curve",                             "%",     "FLOAT", -50, 50, cat, 60)
add(f"{PREFIX}.PERF.ExpectedPower",        "Expected power for current wind speed",                              "kW",    "FLOAT", 0, 20000, cat, 5)
add(f"{PREFIX}.PERF.LostEnergy_Today",     "Lost energy today (downtime + derating)",                            "kWh",   "FLOAT", 0, 1e6, cat, 60)
add(f"{PREFIX}.PERF.LostEnergy_Curtail_Today","Lost energy today due to curtailment",                            "kWh",   "FLOAT", 0, 1e6, cat, 60)
add(f"{PREFIX}.PERF.LostEnergy_Faults_Today","Lost energy today due to faults",                                  "kWh",   "FLOAT", 0, 1e6, cat, 60)
add(f"{PREFIX}.PERF.PerformanceIndex",     "Composite turbine performance index",                                "%",     "FLOAT", 0, 100, cat, 60)
add(f"{PREFIX}.PERF.CO2Avoided_Today",     "CO2 emissions avoided today",                                        "kg",    "FLOAT", 0, 1e6, cat, 300)
add(f"{PREFIX}.PERF.CO2Avoided_Total",     "CO2 emissions avoided lifetime",                                     "kg",    "FLOAT", 0, 1e10, cat, 3600)
add(f"{PREFIX}.PERF.Revenue_Today",        "Estimated revenue today",                                            "USD",   "FLOAT", 0, 1e6, cat, 300)
add(f"{PREFIX}.PERF.Cp",                   "Power coefficient (Cp)",                                             "-",     "FLOAT", 0, 0.6, cat, 5)
add(f"{PREFIX}.PERF.Ct",                   "Thrust coefficient (Ct)",                                            "-",     "FLOAT", 0, 1.5, cat, 5)
add(f"{PREFIX}.PERF.DegradationIndex",     "Equipment degradation index",                                        "%",     "FLOAT", 0, 100, cat, 3600)
add(f"{PREFIX}.PERF.UptimeRatio_Today",    "Uptime ratio today",                                                 "%",     "FLOAT", 0, 100, cat, 60)
add(f"{PREFIX}.PERF.UnplannedDowntime_Today","Unplanned downtime today",                                         "h",     "FLOAT", 0, 24, cat, 60)
add(f"{PREFIX}.PERF.PlannedDowntime_Today","Planned downtime today",                                             "h",     "FLOAT", 0, 24, cat, 60)

# =========================================================
# Output to CSV and JSON
# =========================================================
print(f"Total tags generated: {len(tags)}")

# Save CSV
with open("/home/claude/wind_turbine_tags.csv", "w", newline="") as f:
    fieldnames = ["tag_id","tag_name","description","unit","data_type","min_value","max_value","category","update_interval_sec","is_critical"]
    w = csv.DictWriter(f, fieldnames=fieldnames)
    w.writeheader()
    for t in tags:
        w.writerow(t)

# Save JSON
with open("/home/claude/wind_turbine_tags.json", "w") as f:
    json.dump(tags, f, indent=2)

# Summary by category
from collections import Counter
counts = Counter(t["category"] for t in tags)
print("\nTags per category:")
for c, n in counts.items():
    print(f"  {c}: {n}")